fail_fast: false
repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v6.0.1
    hooks:
      - id: clang-format
        args: [-i]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-merge-conflict
    - id: check-added-large-files
